spring.application.name=radiotv_app_pro

server.port=8081

# Database configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=teste;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=@drS25425643*

# Driver do SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuracoes do Hibernate (opcional)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Pool de conexoes (opcional - HikariCP é padrão no Spring Boot)
spring.datasource.hikari.maximum-pool-size=5


spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Brazil/East

# enviar e-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=drssistemascontrole@gmail.com
spring.mail.password=icvi kdwp xipl cfze 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true